after_script:
  - codeclimate-test-reporter < lcov.info
before_script:
  - npm i -g npm@^3
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - "5"
  - "node"
script:
  - npm test
sudo: required
